feat(gd-14): Refactoring service class, enums, model and controller e…
Shelter-Hub/SpringBoot_App pull request #7
Opened 2023-06-09 03:25 UTC by idmcarvalho

…ndpoint calls

- Refactor of service classes (removing the facade)
- Adding animalMapper to map "from to" animal/animalDTO

2023-06-23 14:44 UTC, igorcruzf requested changes

2023-06-23 14:44 UTC, igorcruzf commented on src/main/java/com/shelterhub/controller/AnimalController.java
> +        try {
acho que o try catch poderia estar dentro do serviço, a camada de controller não teria que saber lidar com exceções de persinsencia ao meu ver

2023-06-23 14:44 UTC, igorcruzf commented on src/main/java/com/shelterhub/controller/AnimalController.java
> +            var location = URI.create(createdAnimal.getId().toString());
particularmente gosto de o post retornar o objeto inteiro ao invés de só o ID, isso pode ser interessante pro front não precisar fazer uma chamada subsequente para redirecionar para a ficha cadastral criada

2023-06-23 14:44 UTC, igorcruzf commented on src/main/java/com/shelterhub/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<ErrorResponse> handlePersistenceFailedException(PersistenceFailedException ex) {
muito bom

2023-06-23 14:44 UTC, igorcruzf commented on src/main/java/com/shelterhub/service/AnimalService.java
> +        var animalToBePersisted = AnimalDTO.toAnimal(animalDTO);
existe algum motivo pra usar como var aqui? acho que se formos utilizar var para as variaveis valeria usar em tudo ao invés de ter diferentes formas em cada método

2023-06-23 14:44 UTC, igorcruzf commented on src/test/java/com/shelterhub/service/AnimalServiceTest.java
> +import static org.junit.jupiter.api.Assertions.*;
wildcard import é melhor evitar: ex: https://www.javadude.com/posts/20040522-import-on-demand-is-evil/

2023-06-23 14:44 UTC, igorcruzf commented on src/main/java/com/shelterhub/dto/AnimalDTO.java
> +    public static Animal toAnimal(AnimalDTO animalDTO) {
se deixar de usar como estático, não precisaria passar o dto como parâmetro

2023-06-23 14:44 UTC, igorcruzf commented on src/main/java/com/shelterhub/dto/AnimalDTO.java
> +    public static Animal toAnimalWithSameAnimalId(AnimalDTO animalDTO, UUID animalId) {
o mesmo q disse acima

2023-06-23 14:44 UTC, igorcruzf commented on src/main/java/com/shelterhub/dto/AnimalDTO.java
> +    public static Animal toAnimalWithSameAnimalId(AnimalDTO animalDTO, UUID animalId) {
na vdd esse método pode morrer até, pq o Id tá sendo passado pelo DTO já

2023-06-23 14:44 UTC, igorcruzf commented on src/main/java/com/shelterhub/service/AnimalService.java
> +        var animalToBePersisted = AnimalDTO.toAnimal(animalDTO);
Fazendo o método deixar de ser estático poderia ser:
```suggestion
        var animalToBePersisted = animalDTO.toAnimal();
```

2023-06-23 14:44 UTC, igorcruzf commented on src/main/java/com/shelterhub/service/AnimalService.java
> +        Animal animalToBePersisted = AnimalDTO.toAnimalWithSameAnimalId(animalDTO, animalId);
como aqui a gnt não tá usando nada do animal buscado, poderia ser:
```suggestion
        Animal animalToBePersisted = animalDTO.toAnimal();
```

2023-06-23 14:44 UTC, igorcruzf commented on src/test/java/com/shelterhub/controller/AnimalControllerTest.java
>      public void shouldCreateAnimal() {
que tal criar um teste para validar se a exceção nova tá sendo capturada pelo handler? 
pode ser um shouldNotCreateAnimalWhenPersistedExceptionIsThrown ou algo do tipo e ai você mocka pro retorno do seu serviço lançar essa exceção e verifica se a resposta vai ser o configurado no handler

2023-06-23 14:44 UTC, igorcruzf commented on src/test/java/com/shelterhub/service/AnimalServiceTest.java
> +public class AnimalServiceTest {
movendo o try catch pra camada de serviço, da pra ter teste unitário com o lançamento de exceção tbm

exemplo de assert:

`assertThrows(PersistedFailedException.class, () -> {
        animalService.create(animalDTO);
    });`

2023-06-29 23:29 UTC, bgvit commented on src/main/java/com/shelterhub/controller/AnimalController.java
> +            var location = URI.create(createdAnimal.getId().toString());
Opa,
Eu acabei colocando dessa forma pra poder seguir o padrão RESTFul... No Padrão RESTFul, quando retornarmos 201, ele prega que devemos devolver o header `location`. O ideal é que eu colocasse o http, porém, só coloquei o id.
Não acho que seria uma boa retornar o objeto que nós mesmos enviamos, talvez valesse a pena se fosse o objeto vindo do banco, só que esse método save não retorna nada.

2023-06-30 00:09 UTC, idmcarvalho commented on src/main/java/com/shelterhub/service/AnimalService.java
> +        var animalToBePersisted = AnimalDTO.toAnimal(animalDTO);
Poderíamos discutir a padronização das criações de variáveis posteriormente, todos juntos para chegarmos a um veredito.

2023-06-30 02:37 UTC, bgvit commented on src/main/java/com/shelterhub/service/AnimalService.java
> +        var animalToBePersisted = AnimalDTO.toAnimal(animalDTO);
Acordamos na call que vamos utilizar o var quando o retorno de uma função não ser tão explícito ou outra maneira em que o var possa auxiliar na legibilidade do código.

Em casos que a legibilidade será melhor com a tipagem explícita, utilizaremos ela ao invés do var.

2023-06-30 02:40 UTC, bgvit commented on src/test/java/com/shelterhub/controller/AnimalControllerTest.java
>      public void shouldCreateAnimal() {
Decidimos puxar essa adição de testes como uma melhoria técnica, vai ser adicionada no linear

2023-06-30 03:10 UTC, bgvit commented on src/main/java/com/shelterhub/service/AnimalService.java
> +        var animalToBePersisted = AnimalDTO.toAnimal(animalDTO);
Colocamos como débito técnico essa refatoração também.

2023-07-02 22:21 UTC, idmcarvalho commented
PR refatorado em pair programming com o Igor Cruz.

2023-07-03 14:41 UTC, bgvit approved these changes

2023-07-03 17:40 UTC, igorcruzf approved these changes

2023-07-03 17:51 UTC, merged